INSERT INTO Employee (AADHAR_ID, name, LOCATION, IS_COVID_AFFECTED, IS_IN_QUARANTINE, NO_OF_QUARANTINE_DAYS_LEFT, IS_COVID_CURED)
VALUES ('123', 'Tom', 'Chennai', 'Y', 'Y', '20', 'N');
INSERT INTO Employee (AADHAR_ID, name, LOCATION, IS_COVID_AFFECTED, IS_IN_QUARANTINE, NO_OF_QUARANTINE_DAYS_LEFT, IS_COVID_CURED)
VALUES ('124', 'Sam', 'Mumbai', 'Y', 'N', 20, 'N');
INSERT INTO Employee (AADHAR_ID, name, LOCATION, IS_COVID_AFFECTED, IS_IN_QUARANTINE, NO_OF_QUARANTINE_DAYS_LEFT, IS_COVID_CURED)
VALUES ('125', 'Mike', 'Delhi', 'N', 'N', '20', 'N');


